name: Setup dev version after release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'merge') && contains(github.event.head_commit.message, 'master')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Get version from POM
      if: "contains(github.ref, 'develop')"
      run: |
        VERSION=($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr "." "\n"))

        echo "MAJOR=${VERSION[0]}" >> $GITHUB_ENV
        echo "MINOR=${VERSION[1]}" >> $GITHUB_ENV
        echo "PATCH=${VERSION[2]}" >> $GITHUB_ENV 

    - name: Setup development version
      if: "contains(github.ref, 'develop')"
      run: |
        NEW_VERSION="$((MAJOR)).$((MINOR)).$((PATCH+1))-build1"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
    - name: Update POM Version
      if: "contains(github.ref, 'develop')"
      run: |
        echo "New version  is: ${NEW_VERSION}"
        mvn versions:set versions:update-child-modules -DnewVersion=${NEW_VERSION} -DprocessAllModules -DgenerateBackupPoms=false
    - name: Commit files
      if: "contains(github.ref, 'develop')"
      run: |
        git config --local user.email "advanzia_bot@backbase.com"
        git config --local user.name "bb-advanzia-bot"
        git commit -m "[skip bump] version bump" -a
    - name: Push changes
      if: "contains(github.ref, 'develop')"
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

