# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip bump]') && !contains(github.event.head_commit.message, 'nobump/')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get version from POM
      if: "contains(github.ref, 'master')"
      run: |
        VERSION=($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr "-" "\n"))

        VERSION_1=( $(echo ${VERSION[0]} | tr "." "\n") )
        VERSION_2=`echo ${VERSION[1]} | tr -dc '0-9'`
    
        echo "MAJOR=${VERSION_1[0]}" >> $GITHUB_ENV
        echo "MINOR=${VERSION_1[1]}" >> $GITHUB_ENV
        echo "PATCH=${VERSION_1[2]}" >> $GITHUB_ENV 
        echo "BUILD=${VERSION_2}" >> $GITHUB_ENV

    - name: Setup PR version
      if: "contains(github.ref, 'master')"
      run: |
        NEW_VERSION="$((MAJOR)).$((MINOR)).$((PATCH))-build$((BUILD+1))"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
    - name: Setup major version
      if: "contains(github.ref, 'master') && contains(github.event.head_commit.message, 'bump major')"
      run: |
        NEW_VERSION="$((MAJOR+1)).$((MINOR)).$((PATCH))-build1"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
    - name: Update POM Version
      if: "contains(github.ref, 'master')"
      run: |
        echo "New version  is: ${NEW_VERSION}"
        mvn versions:set versions:update-child-modules -DnewVersion=${NEW_VERSION} -DprocessAllModules -DgenerateBackupPoms=false
    - name: Commit files
      if: "contains(github.ref, 'master')"
      run: |
        git config --local user.email "advanzia_bot@backbase.com"
        git config --local user.name "bb-advanzia-bot"
        git commit -m "[skip bump] version bump" -a
    - name: Push changes
      if: "contains(github.ref, 'master')"
      uses: ad-m/github-push-action@master

